name: luncheo

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: luncheo
      POSTGRES_USER: luncheo
      POSTGRES_DB: luncheo-dev
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - .:/app/
      - luncheo_pgdata_dev:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_luncheo
    image: dpage/pgadmin4:7.0
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - ./.config/docker/pgadmin4/servers.json:/pgadmin4/servers.json
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  luncheo_pgdata_dev:
    driver: local