hello_world:
  path: /hello-world
  controller: App\Example\API\Controller\ExampleController::helloWorld
  methods: [GET]

get_changelog:
  path: /api/examples
  controller: App\Example\API\Controller\ExampleController::getAll
  methods: [GET]