hello_world:
  path: /hello-world
  controller: App\Controller\ExamplController::helloWorld
  methods: [GET]

get_changelog:
  path: /api/examples
  controller: App\Controller\ExampleController::getAll
  methods: [GET]