order_get_all:
  path: /order/all
  controller: App\Controller\OrderController::getAll
  methods: [GET]

create_order:
  path: /order
  controller: App\Controller\OrderController::createOrder
  methods: [POST]

add_order_line:
  path: /order/line
  controller: App\Controller\OrderController::addOrderLine
  methods: [POST]