order_get_all:
  path: /order/all
  controller: App\Controller\OrderController::getAll
  methods: [GET]

create_order:
  path: /order
  controller: App\Controller\OrderController::createOrder
  methods: [POST]

upsert_order_line:
  path: /order/line
  controller: App\Controller\OrderController::upsertOrderLine
  methods: [POST, PATCH, PUT]