order_get_all:
  path: /order/all
  controller: App\Controller\OrderController::getAll
  methods: [GET]

order_get_by_user:
  path: /order/{userId}
  controller: App\Controller\OrderController::getByUserId
  methods: [GET]
  
create_order:
  path: /order
  controller: App\Controller\OrderController::createOrder
  methods: [POST]

pay_order:
  path: /order
  controller: App\Controller\OrderController::payOrder
  methods: [PATCH, PUT]

upsert_order_line:
  path: /order-line
  controller: App\Controller\OrderController::upsertOrderLine
  methods: [POST, PATCH, PUT]

remove_order:
  path: /order/{id}
  controller: App\Controller\OrderController::removeOrder
  methods: [DELETE]

remove_order_line:
  path: /order-line
  controller: App\Controller\OrderController::removeOrderLine
  methods: [DELETE]