get_all:
  path: /user/all
  controller: App\Controller\UserController::getAll
  methods: [GET]

get_by_id:
  path: /user/{id}
  controller: App\Controller\UserController::getUserById
  methods: [GET]
