get_all:
  path: /user/all
  controller: App\Controller\UserController::getAll
  methods: [GET]

get_by_id:
  path: /user/{id}
  controller: App\Controller\UserController::getUserById
  methods: [GET]

register:
  path: /user/register
  controller: App\Controller\UserController::register
  methods: [POST]

login:
  path: /user/login
  controller: App\Controller\UserController::login
  methods: [POST]
